WebAppMVC/Controllers/OperadorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dominio;
using Microsoft.AspNetCore.Http;

namespace WebAppMVC.Controllers
{
    public class OperadorController : Controller
    {
        Sistema s = Sistema.Instancia;

        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("LogueadoRol") == "OPE")
            {
                List<Seleccion> selecciones = s.GetSelecciones();
                return View(selecciones);
            }
            return RedirectToAction("Error");
            }

        public IActionResult Partidos() 
        {
            if (HttpContext.Session.GetString("LogueadoRol") == "OPE")
            {
                List<Partido> partidos = s.GetPartidos();
                return View(partidos);
            }
            return RedirectToAction("Error");
            }

        public IActionResult Reseñas(int id)
        {
            List<Reseña> reseñas = s.GetPeriodistaPorId(id).GetReseñas();
            return View(reseñas);
        }

        public IActionResult Periodistas()
        {
            if (HttpContext.Session.GetString("LogueadoRol") == "OPE")
            {
                List<Periodista> listaPeriodistas = s.GetPeriodistas();
                return View(listaPeriodistas);
            }
            return RedirectToAction("Error");
        }

        public IActionResult EntreFechas()
        {
            if (HttpContext.Session.GetString("LogueadoRol") == "OPE")
            {
                return View();
            }
            return RedirectToAction("Error");
        }

        [HttpPost]
        public IActionResult EntreFechas(DateTime fecha1, DateTime fecha2)
        {
            if(fecha1 > fecha2) //las da vuelta si el usuario las ingresa al revés
            {
                DateTime auxFecha = fecha1;
                fecha1 = fecha2;
                fecha2 = auxFecha;
            }

            List <Partido> aux = s.PartidosEntreFecha(fecha1, fecha2);

            return View(aux);
        }

        public IActionResult PartidosRoja()
        {
            if (HttpContext.Session.GetString("LogueadoRol") == "OPE")
            {
                return View();
            }
            return RedirectToAction("Error");
        }

        [HttpPost]
        public IActionResult PartidosRoja(string mail)
        {
            List<Partido> lista = s.PartidosRojaSegunPeriodista(mail);
            return View(lista); 
        }

        public IActionResult MasGoles()
        {
            if (HttpContext.Session.GetString("LogueadoRol") == "OPE")
            {
                List<Seleccion> selecciones = s.SeleccionConMasGoles();
                return View(selecciones);
            }
            return RedirectToAction("Error");
        }

        public IActionResult DetallesPartido(int id)
        {
            s.GetPartidoPorID(id).Resultado();
            return View(s.GetPartidoPorIDConCasteo(id));
        }
    }
}

WebAppMVC/Controllers/PeriodistaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dominio;
using Microsoft.AspNetCore.Http;

namespace WebAppMVC.Controllers
{
    public class PeriodistaController : Controller
    {
        Sistema s = Sistema.Instancia;
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("LogueadoRol") != null)
            {
                List<Partido> partidos = s.GetPartidos();
                return View(partidos);
            }
            return RedirectToAction("Error", "Home");
            }

        public IActionResult Reseñas()
        {
            if (HttpContext.Session.GetString("LogueadoRol") == "PER")
            {
                Periodista periodista = s.GetPeriodista(HttpContext.Session.GetInt32("LogueadoId"));
                List<Reseña> reseñas = periodista.GetReseñas();
                return View(reseñas);
            }
            return RedirectToAction("Error", "Home");
            }

        public IActionResult CreateReseña()
        {
            if (HttpContext.Session.GetString("LogueadoRol") == "PER")
            {
                return View();
            }
            return RedirectToAction("Error", "Home");
            }

        [HttpPost]
        public IActionResult CreateReseña(Reseña r, int pID) 
        {
            try
            {
                    s.LlenarDatosReseña(r, pID, HttpContext.Session.GetString("LogueadoMail"));
                    s.AltaReseña(r);
                    ViewBag.msg = "Reseña dada de alta con éxito.";
                }
                catch (Exception e)
                {
                    ViewBag.msg = e.Message;
                }
                return View();
            }
        }
    }

WebAppMVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.Session.GetInt32("LogueadoId") == null)
                        {
                            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppMVC</a>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Registro">Registro</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Iniciar sesión</a>
                            </li>
                        }

                        @if (Context.Session.GetString("LogueadoRol") == "PER")
                        {
                            <a class="navbar-brand" asp-area="" asp-controller="Periodista" asp-action="Index">WebAppMVC</a>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Periodista" asp-action="Index">Partidos cerrados</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Periodista" asp-action="Reseñas">Listado de reseñas realizadas</a>
                            </li>
                        }

                        @if (Context.Session.GetString("LogueadoRol") == "OPE")
                        {
                            <a class="navbar-brand" asp-area="" asp-controller="Operador" asp-action="Index">WebAppMVC</a>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Operador" asp-action="Periodistas">Periodistas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Operador" asp-action="Partidos">Partidos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Operador" asp-action="Index">Selecciones</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Operador" asp-action="EntreFechas">Partidos entre dos fechas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Operador" asp-action="MasGoles">Selección/es con más goles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Operador" asp-action="PartidosRoja">Partidos con roja reseñados por periodista</a>
                            </li>
                        }

                        @if (Context.Session.GetInt32("LogueadoId") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Cerrar sesión</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebAppMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>